spring:
  application:
    name: isael-persona-rest
  r2dbc:
    url: r2dbc:h2:mem:///testdb;DB_CLOSE_DELAY=-1;CASE_INSENSITIVE_IDENTIFIERS=TRUE
    username: ${SECRET_USERNAME:sa}
    password: ${SECRET_PASSWORD:password}
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

server:
  port: ${APP_PORT:8085}