apiVersion: v1
kind: Secret
metadata:
  name: jeanpiervicente-api-secret
  namespace: jeanpiervicente-api-ms
  labels:
    app: jeanpiervicente-api
type: Opaque
data:
  username: c2E=
  password: cGFzc3dvcmQ=